### ISSUE TITLE
Requests to /static/manifest.json do not respect cookies and headers

### ISSUE THREAD

**Issue by pecigonzalo** [morpheus65535/bazarr#1084]
**Describe the bug**
Im running Bazarr behind https://github.com/authelia/authelia and Im getting 
```
DataTables warning: table id=movies - Ajax error. For more information about this error, please see http://datatables.net/tn/7
```

Checking the Network and Console with Chrome Dev Tools I can see its failing to get `/static/manifest.json` because its getting redirected to authelia for authentication. This is because Bazarr does not respect the cookies and headers for the domain and sends the request to the file without the cookie based auth.

**To Reproduce**
1. Setup Bazarr
2. Setup [Authelia](https://github.com/authelia/authelia)
3. Setup [NGINX](https://www.authelia.com/docs/deployment/supported-proxies/nginx.html)

**Expected behavior**
Requests to all resources should respect cookies and auth

**Software (please complete the following information):**
Bazarr Version: 0.9.0.2
Sonarr Version: 2.0.0.5344
Radarr Version: 0.2.0.1504
Operating System:
Linux-4.19.0-8-amd64-x86_64-with

**Comment by AliMickey** [comment]
Here is a solution, unless this is a separate problem its not a cookie/header issue rather a buffer issue with authelia. 

Try this out first. 
https://github.com/morpheus65535/bazarr/issues/1065

**Comment by AliMickey** [comment]
Also for @morpheus65535, here is the code block needed to add to the wiki. There seems to be no pr capability for wikis.


`
### Authelia

> *Note: The default buffer_size is 4096, double that seems to fix any loading issues with Bazarr.*

```
access_control:
  default_policy:
  rules:
    - domain:
        - bazarr.<domain>.com
      resources:
        - '^/api/.*$'
      policy: bypass

server:
  read_buffer_size: 8192
  write_buffer_size: 8192
  path: authelia
```
`
