### ISSUE TITLE
TypeError: NoneType object is not iterable when attempting to update list (Job Sync episodes with Sonarr raised an exception)

### ISSUE THREAD

**Issue by typhoe** [morpheus65535/bazarr#1633]
**Describe the bug**
On a fresh install of Bazarr, I get the following error logs (this occurs on Sonarr only):

```Job "Sync episodes with Sonarr (trigger: interval[1:00:00], next run at: 2021-12-07 05:46:00 CET)" raised an exception```

```
Traceback (most recent call last):

  File "/app/bin/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "/app/bin/bazarr/get_episodes.py", line 66, in sync_episodes

    item = [x for x in episodeFiles if x[\'id\'] == episode[\'episodeFileId\']]

TypeError: \'NoneType\' object is not iterable
```

**To Reproduce**
This happens on a fresh install of bazarr from docker container hotio
```
  bazarr:
    container_name: bazarr
    image: hotio/bazarr:release
    depends_on: 
      - radarr
      - sonarr
    restart: unless-stopped
    networks: 
      - media-net
    ports:
      - 6767:6767
    volumes:
      - /zfs/data/docker/bazarr/config:/config
      - /volume1/data:/data
    environment:
      - TZ=Europe/London
      - UMASK=002
      - PGID=100
      - PUID=888
```

**Expected behavior**
Episodes subtitles should sync

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v1.0.12021-11-19
 - Radarr: 3.2.2.5080
 - Sonarr: 3.0.6.1342
 - OS: Linux docker 5.13.19 (inside Proxmox LXC container)
