### ISSUE TITLE
Bazarr fails to load GUI in any form while throwing no major errors

### ISSUE THREAD

**Issue by arnavpraneet** [morpheus65535/bazarr#1927]
Expected Behavior

Bazarr GUI should load when navigating to port 6767
Current Behavior

Unable to connect on all browsers and machines
Steps to Reproduce

    Bazarr working normally in setup
    2.Stops working

Environment

OS: Ubuntu 22.04.1 LTS Jammy
CPU architecture: arm64/aarch64
How docker service was installed:
Through LMDS (https://greenfrognest.com/), also tried by installing through normal docker-compose from (https://bazarr.media/), also tried Docker Run
Command used to create docker container (run/create/compose/screenshot)
```
bazarr:
    image: linuxserver/bazarr:arm64v8-1.0.4
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - UMASK_SET=022 #optional
    volumes:
      - ./volumes/bazarr/config:/config
      - ./media/movies:/movies
      - ./media/tvshows:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
```
(Above is specifically trying with an older, version, earlier it was latest)
Docker logs

[_bazarr_logs(1).txt](https://github.com/linuxserver/docker-bazarr/files/9335843/_bazarr_logs.1.txt)
Similar logs presenting every time.

Machine is VPS in Oracle Cloud, Bazarr worked perfectly before along with the rest of the arr stack, a cron script uploads all the downloads to a rclone gdrive mergerfs mount every hour.
