### ISSUE TITLE
Bazarr cache files are writable by other users (linux file permissions issue)

### ISSUE THREAD

**Issue by Practicalbutterfly5** [morpheus65535/bazarr#2084]
**Describe the bug**
Cache files of bazarr are created with permission (0666/-rw-rw-rw-). This is dangerous permission as it allows other users write access to these files. Also, it keeps triggering alerts in the security products like wazuh for the same reason.

**Expected behavior**
Cache files permission should be 644 or lower

**Software (please complete the following information):**
 - Docker version: Linuxserver.io version:- v1.1.4-ls184 Build-date:- 2023-02-25T22:37:02-06:00
 - OS: Ubuntu LTS 22.04

**Additional context**
Output of stat
```
~# stat /root/plex/data/bazarr/cache/*
  File: /root/plex/data/bazarr/cache/36313339356664663162663266373861356536653062353536393331613239353634396235356561
  Size: 239             Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d      Inode: 2074627     Links: 1
Access: (0666/-rw-rw-rw-)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-03-04 17:16:16.011280092 +0530
Modify: 2023-03-04 15:00:39.899872205 +0530
Change: 2023-03-04 15:00:39.903872243 +0530
 Birth: 2023-03-01 16:45:03.760029674 +0530
```

Docker-compose
```
...
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: plex_bazarr
    environment:
      - PUID=0
      - PGID=0
    volumes:
      - ./data/bazarr:/config
      - ./downloads:/data
    ports:
      - 127.0.0.1:6767:6767
    restart: unless-stopped
...
```
