### ISSUE TITLE
UnicodeEncodeError on Docker installation Exception info: 'latin-1'

### ISSUE THREAD

**Issue by garanda21** [morpheus65535/bazarr#2116]
**Describe the bug**
Using latest tag from docker image, I get error `UnicodeEncodeError. Exception info: 'latin-1'` if series name has an apostrophe. On previous bazaar versions it worked fine. The error is coming from `subdivx` provider.

**To Reproduce**
1. Go to 'Series' 
2. Click on a serie that has an accent or apostrophe on its name
3. Use manual search from any episode.
4. From the result list, choose subdivx to download.
5. Go to the log to see error

**Expected behavior**
Download subtitule.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.2.0
 - Sonarr version: 3.0.10.1567
 - Docker image:[https://docs.linuxserver.io/images/docker-bazarr]( https://docs.linuxserver.io/images/docker-bazarr)

**Additional context**
Log lines showing error:

```
10/04/2023 13:28:44|INFO    |root |Throttling subdivx for 10 minutes, until 23/04/10 13:38, because of: UnicodeEncodeError. Exception info: 'latin-1'|

10/04/2023 13:28:44|ERROR   |root |BAZARR No valid Subtitles file found for this file: /tv/Grey's Anatomy/Season 19/Greys.Anatomy.S19E13.1080p.WEB.h264-ELEANOR[rarbg].mkv|'NoneType: None'|
```

docker-compose.yml:

```
version: "2.1"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1037
      - PGID=65537
      - TZ=Europe/Madrid
    volumes:
      - /volume1/docker/bazarr:/config
      - /volume1/Public/Shared Videos/Downloads:/tv
      - /volume1/Movies/Downloads:/movies
    ports:
      - 6767:6767
    restart: unless-stopped
```
