### ISSUE TITLE
"Unknown action" when trying to login

### ISSUE THREAD

**Issue by ROODAY** [morpheus65535/bazarr#2136]
**Describe the bug**
I had setup bazarr and it was working fine and now all of a sudden I can't login, getting the error "Unknown action". Based on this file: https://github.com/morpheus65535/bazarr/blob/b485dd9c716b784b9b945d5093161c60a8e21f80/bazarr/api/system/account.py it should only say that if the action isn't login or logout, but this is the URL being hit: `https://mydomain/api/system/account?action=login`. Not sure what's going on here.

**To Reproduce**
Here is my docker compose
```
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:bazarr
      - TP_THEME=dracula
    volumes:
      - /home/bazarr:/config
      - /servercontent/movies:/movies #optional
      - /servercontent/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
```

After starting it up, I went into settings and set a form based authentication, and then randomly I got this error after some time. If I go into the config.ini and set auth to None I can get back in, but I want to have a password setup.

**Expected behavior**
Login should just work.

**Screenshots**
![image](https://user-images.githubusercontent.com/5439867/236574959-901474d6-c53e-4a2c-8e49-7d86cfa0e782.png)

**Software (please complete the following information):**
 - Bazarr: v1.2.1
 - OS: Docker on Ubuntu 22
