### ISSUE TITLE
I can't access the configuration page

### ISSUE THREAD

**Issue by Finallf** [morpheus65535/bazarr#2200]
**Describe the bug**
The bazarr webpage does not open.
ERR_CONNECTION_REFUSED

**To Reproduce**
1. Go to 'any browser'
2. Click on 'IP_Server:6767'

**Expected behavior**
That opened the Bazarr web ui so I could configure

**Screenshots**
I have 9 other containers in my stack and they all work, only bazarr doesn't open the web ui
![bazarr01](https://github.com/morpheus65535/bazarr/assets/8967685/7f6001da-cff3-48aa-8043-834a1b74822c)
With the exception of the bazaar of the others work

**Software (please complete the following information):**
 - Bazarr: lscr.io/linuxserver/bazarr:latest
 - Radarr version 4.6.4.7568-ls179 by [linuxserver.io](https://linuxserver.io/)
 - Sonarr version 3.0.10.1567-ls199 by [linuxserver.io](https://linuxserver.io/)
 - OS: Debian 11 + docker

**Additional context**
I tried other images as well as hotio and the same error.
ha tried changing the TZ, port, etc.
log:
```
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support the app dev(s) visit:
Bazarr: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[custom-init] No custom files found, skipping...
```

Compose:
```
version: "3.8"
networks:
  mediarr:
    external: false
    name: mediarr
services:
  bazarr: # Subtitle catcher
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${NAS}/configs/bazarr:/config # config files
      - ${NAS}:/movies # movies folder
    networks:
      - mediarr
    ports:
      - 6767:6767
    restart: unless-stopped
```
.env
```
NAS=/mnt/Storage/Media
TZ=America/Sao_Paulo
PUID=1000
PGID=1000
```
