### ISSUE TITLE
WebUI "ERR_CONNECTION_RESET" won't open

### ISSUE THREAD

**Issue by Neobond** [morpheus65535/bazarr#2881]
**Describe the bug**
I can't seem to be able to load the webui, howeever it is conencted to Sonarr and Radarr (no errors there)

**To Reproduce**
1. on going to 'http://localip:6767'

**Screenshots**
![Image](https://github.com/user-attachments/assets/92ff2467-6ca2-4d29-b0b0-c7134f607c13)

**Software (please complete the following information):**
 - Bazarr: Linuxserver.io version: v1.5.1-ls296
 - Radarr version Linuxserver.io version: 5.20.2.9777-ls264
 - Sonarr version Linuxserver.io version: 4.0.14.2939-ls275
 - OS: DSM 7.2 (installed in Container Manager)

**Additional context**
I screenshotted what looks like a bunch of failures reported after the container was started.

`/usr/include/c++/14.2.0/bits/stl_vector.h:1130: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = ZenLib::Ztring; _Alloc = std::allocator<ZenLib::Ztring>; reference = ZenLib::Ztring&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.`

IP is set to 0.0.0.0 in config.yml

My Docker compose:
```
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/Amsterdam
      - UMASK=022
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume2/data:/data
    ports:
      - 8989:8989/tcp
    network_mode: synobridge  
    security_opt:
      - no-new-privileges:true
    restart: always
    
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/Amsterdam
      - UMASK=022
    volumes:
      - /volume1/docker/radarr:/config
      - /volume2/data:/data
    ports:
      - 7878:7878/tcp
    network_mode: synobridge  
    security_opt:
      - no-new-privileges:true
    restart: always

  unpackerr:
    container_name: unpackerr
    image: ghcr.io/hotio/unpackerr
    labels:
     io.portainer.accesscontrol.users: public
    environment:
      - PUID=1027
      - PGID=65536
      - TZ=Europe/Amsterdam
      - UMASK=002
    volumes:
      - /volume1/docker/unpackerr:/config
      - /volume2/data:/data
    network_mode: synobridge  
    security_opt:
      - no-new-privileges:true
    restart: always

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1027 #CHANGE_TO_YOUR_UID
      - PGID=65536 #CHANGE_TO_YOUR_GID
      - TZ=Europe/Amsterdam #CHANGE_TO_YOUR_TZ
      - UMASK=022
    volumes:
      - /volume1/docker/bazarr:/config
      - /volume2/data:/data
    ports:
      - 6767:6767/tcp
    network_mode: synobridge  
    security_opt:
      - no-new-privileges:true
    restart: always
```
