### ISSUE TITLE
Traefik reverse proxy setup

### ISSUE THREAD

**Issue by mikafouenski** [morpheus65535/bazarr#627]
Hello,

I'm trying to setup the docker image of Bazarr from `linuxserver` with the traefik reverse proxy.
I tried to migrate the nginx config provided in the [wiki](https://github.com/morpheus65535/bazarr/wiki/Reverse-proxy-Nginx).

I'm using the [PathPrefixStrip](https://docs.traefik.io/v1.7/basics/#matchers) matcher but when I go to `http://localhost/bazarr` I get  a 303 which redirect me to `http://localhost/wizard` which don't exist. And if y go manually to `http://localhost/bazarr/wizard`, I get the same result as before with every static resource.

### To Reproduce
`docker-compose.yml`
```yaml
version: '3.5'

networks:
  traefik-network:

services:
  bazarr:
    image: linuxserver/bazarr
    labels:
      - "traefik.enable=true"
      - "traefik.backend=bazarr"
      - "traefik.docker.network=traefik-network"
      - "traefik.port=6767"
      - "traefik.frontend.rule=PathPrefixStrip:/bazarr"
    networks:
      traefik-network:

  traefik:
    image: traefik:v1.7
    ports:
      - '80:80'
    command: >
      --logLevel=DEBUG
      --defaultEntryPoints=http
      --entrypoints=Name:"http Address::80"
      --docker
      --docker.domain=localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      traefik-network:
```
And then `docker-compose up`

![image](https://user-images.githubusercontent.com/11093325/66653587-ac9ffa80-ec38-11e9-971b-be72834a7abf.png)

### Software:
 - Bazarr: `0.8.2.4`
 - Docker image `linuxserver/bazarr:latest`

Thanks,
Mika

**Comment by morpheus65535** [comment]
Did you configure base path in Settings/General?

**Comment by mikafouenski** [comment]
Hello @morpheus65535,

> Q: I don't reach the WebUI! 
> R: Sure, go to the WebUI in Settings > General 

:smirk:

Indeed we need to tell Bazarr to prefix everything.

After picking at the code I've seen that you are loading a [`config.ini`](https://github.com/morpheus65535/bazarr/blob/master/bazarr/config.py#L142) file as the main configuration.

As the app doesn't use relative redirection, we can't utilize [`PathPrefixStrip`](https://docs.traefik.io/v1.7/basics/#matchers) as matcher, we need to use just `PathPrefix` with `base_url` settings of Bazarr.

### How to make it work:

All trailings `/` are important!

`config.ini`:
```ini
[general]
base_url = /a/bazarr/
```

`docker-compose.yml`:
```yaml
version: '3.5'

networks:
  traefik-network:

services:
  bazarr:
    image: linuxserver/bazarr
    labels:
      - "traefik.enable=true"
      - "traefik.backend=bazarr"
      - "traefik.docker.network=traefik-network"
      - "traefik.port=6767"
      - "traefik.frontend.rule=PathPrefix:/bazarr"
    volumes:
      - ./config.ini:/config/config.ini
    networks:
      traefik-network:

  traefik:
    image: traefik:v1.7
    ports:
      - '80:80'
    command: >
      --logLevel=DEBUG
      --defaultEntryPoints=http
      --entrypoints=Name:"http Address::80"
      --docker
      --docker.domain=localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      traefik-network:
```

And when completing the wizard, you need to input `/a/bazarr/` in the base path as the `config.ini` file will get overwritten...

Anyway, I look forward to testing Bazarr as the Jellyfin Opensubtitle support sometimes doesn't get the good release at all.

Regards,
Mika
